commitMessage : add missing commands to nodetool-completion (CASSANDRA-14916)

diff --git a/bin/cassandra b/bin/cassandra
--- a/bin/cassandra
+++ b/bin/cassandra
@@ -30,7 +30,6 @@
 #   JVM_OPTS -- Additional arguments to the JVM for heap size, etc
 #   JVM_ON_OUT_OF_MEMORY_ERROR_OPT -- The OnOutOfMemoryError JVM option if specified
 #   CASSANDRA_CONF -- Directory containing Cassandra configuration files.
-#   CASSANDRA_LOG_DIR -- Directory containing logs(default: $CASSANDRA_HOME/logs).
 #
 # As a convenience, a fragment of shell is sourced in order to set one or
 # more of these variables. This so-called `include' can be placed in a 
@@ -67,9 +66,6 @@
 # POSIX sh and Solaris sh. This means, in particular, no $(( )) and no $( ).
 
 # If an include wasn't specified in the environment, then search for one...
-
-jvmoptions_variant="-server"
-
 if [ "x$CASSANDRA_INCLUDE" = "x" ]; then
     # Locations (in order) to use when searching for an include file.
     for include in "`dirname "$0"`/cassandra.in.sh" \
@@ -85,6 +81,27 @@ if [ "x$CASSANDRA_INCLUDE" = "x" ]; then
 # ...otherwise, source the specified include.
 elif [ -r "$CASSANDRA_INCLUDE" ]; then
     . "$CASSANDRA_INCLUDE"
+fi
+
+# Use JAVA_HOME if set, otherwise look for java in PATH
+if [ -n "$JAVA_HOME" ]; then
+    # Why we can't have nice things: Solaris combines x86 and x86_64
+    # installations in the same tree, using an unconventional path for the
+    # 64bit JVM.  Since we prefer 64bit, search the alternate path first,
+    # (see https://issues.apache.org/jira/browse/CASSANDRA-4638).
+    for java in "$JAVA_HOME"/bin/amd64/java "$JAVA_HOME"/bin/java; do
+        if [ -x "$java" ]; then
+            JAVA="$java"
+            break
+        fi
+    done
+else
+    JAVA=java
+fi
+
+if [ -z $JAVA ] ; then
+    echo Unable to find java executable. Check JAVA_HOME and PATH environment variables. >&2
+    exit 1;
 fi
 
 # If numactl is available, use it. For Cassandra, the priority is to
@@ -106,10 +123,6 @@ fi
 
 if [ -f "$CASSANDRA_CONF/cassandra-env.sh" ]; then
     . "$CASSANDRA_CONF/cassandra-env.sh"
-fi
-
-if [ -z "$CASSANDRA_LOG_DIR" ]; then
-  CASSANDRA_LOG_DIR=$CASSANDRA_HOME/logs
 fi
 
 # Special-case path variables.
@@ -176,7 +189,7 @@ launch_service()
     props="$3"
     class="$4"
     cassandra_parms="-Dlogback.configurationFile=logback.xml"
-    cassandra_parms="$cassandra_parms -Dcassandra.logdir=$CASSANDRA_LOG_DIR"
+    cassandra_parms="$cassandra_parms -Dcassandra.logdir=$CASSANDRA_HOME/logs"
     cassandra_parms="$cassandra_parms -Dcassandra.storagedir=$cassandra_storagedir"
 
     if [ "x$pidpath" != "x" ]; then
@@ -209,7 +222,7 @@ launch_service()
 }
 
 # Parse any command line options.
-args=`getopt vRfhp:bD:H:E: "$@"`
+args=`getopt vfhp:bD:H:E: "$@"`
 eval set -- "$args"
 
 classname="org.apache.cassandra.service.CassandraDaemon"
@@ -232,10 +245,6 @@ while true; do
             "$JAVA" -cp "$CLASSPATH" "-Dlogback.configurationFile=logback-tools.xml" org.apache.cassandra.tools.GetVersion
             exit 0
         ;;
-        -R)
-            allow_root="yes"
-            shift
-        ;;
         -D)
             properties="$properties -D$2"
             shift 2
@@ -250,25 +259,20 @@ while true; do
         ;;
         --)
             shift
-            if [ "x$*" != "x" ] ; then
-                echo "Error parsing arguments! Unknown argument \"$*\"" >&2
-                exit 1
-            fi
             break
         ;;
         *)
-            echo "Error parsing arguments! Unknown argument \"$1\"" >&2
+            echo "Error parsing arguments!" >&2
             exit 1
         ;;
     esac
 done
 
-if [ "x$allow_root" != "xyes" ] ; then
-    if [ "`id -u`" = "0" ] || [ "`id -g`" = "0" ] ; then
-        echo "Running Cassandra as root user or group is not recommended - please start Cassandra using a different system user."
-        echo "If you really want to force running Cassandra as root, use -R command line option."
-        exit 1
-    fi
+# see CASSANDRA-7254
+"$JAVA" -cp "$CLASSPATH" $JVM_OPTS 2>&1 | grep -q 'Error: Exception thrown by the agent : java.lang.NullPointerException'
+if [ $? -ne "1" ]; then 
+    echo Unable to bind JMX, is Cassandra already running?
+    exit 1;
 fi
 
 # Start up the service
